baseurl = "http://fisiu.github.io"
languageCode = "pl-PL"
title = "System.out.println"
# Enable comments by entering your Disqus shortname
disqusShortname = "fisiu-github-io"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-2256304-7"
# Define the number of posts per page
paginate = 10
paginatePath = "strona"
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
# syntax highlighting
pygmentsuseclasses = true
# emoji support
enableEmoji = true


[permalinks]
    # post = "/:year/:month/:day/:slug"
    post = "/:year/:month/:slug"


[params]
    # Tell me who you are
    author = "Mariusz Fik"
    bio = "Software engineer • Cyborg • openSUSE Geeko"
    location = "Oświęcim/PL"
    site_description = "Jakiś opis strony"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "img/avatar.jpg"
    logo = "css/images/logo.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Start"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Archiwum"
    link   = "archiwum/"
# [[params.menu]]
#     before = false
#     label  = "Tagi"
#     link   = "tags/"

# [[params.menu]]
#     before = false
#     label  = "Kategorie"
#     link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/Fisiu"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "Fisiu"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = "MariuszFik"
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "Fisiu"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = false
    tag_cloud = true
